import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import { Inter } from 'next/font/google'

// Import { someNamedInport } from 'somelibrary'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) { //function start
  

  //funciton return statment
  return (
    <html lang="en">
        <body className={inter.className}>
            {children}
        </body>
    </html>
  )

} //fuction End
